# try catch else

try:
    print("in try")    
    print(1/1)
    print("after division by zero")
except:
    print("exception caught")
else:
    print("i am else")
finally:
    print("finally block")